### PR TITLE
Update userChrome.css

### PR DESCRIPTION
**Pull request by amydevs**
Added dark, Edge style context menus.

### CODE REVIEW

**Comment by kube** [comment]
Thanks!

**Comment by mengelbrecht** [comment]
Now the context menu is dark even when the light theme is selected. Is that intentional?

**Comment by kube** [comment]
@mengelbrecht I reverted the commit.
Some work needs to be done on this theme to clean the code, which was just an experimentation.
Colors should not belong to this CSS stylesheet, as the goal here is to stay compatible with Firefox Colors.

**Comment by amydevs** [comment]
I'll try to make it work in the time being.

**Comment by kube** [comment]
@jy1263 Colors should not be in this file, except for some particular cases. But the idea is not to match entirely the Edge Color Scheme, but rather to match shape and design.
We should be able to load a custom color scheme from Firefox Color.

Here is an example:
Screenshot 2019-10-18 at 15 25 44

**Pull request merged**
